version: "3"
services:
  haproxy:
    build: ./haproxy
    ports:
      - "8080:80"
      - "8081:8080"

  web1:
    image: rplace-server/server:0.1.0
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka1:9092,kafka2:9092,kafka3:9092"
      KAFKA_TOPIC: "rplace"
      KAFKA_GROUP: "web1"
  web2:
    image: rplace-server/server:0.1.0
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka1:9092,kafka2:9092,kafka3:9092"
      KAFKA_TOPIC: "rplace"
      KAFKA_GROUP: "web2"
  web3:
    image: rplace-server/server:0.1.0
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka1:9092,kafka2:9092,kafka3:9092"
      KAFKA_TOPIC: "rplace"
      KAFKA_GROUP: "web3"

  redis:
    build: ./redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data

  zookeeper:
    image: zookeeper

  kafka1:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: kafka1
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_BROKER_ID: 1
      KAFKA_MESSAGE_MAX_BYTES: 512
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_CREATE_TOPICS: "rplace:1:3:compact"
      KAFKA_LOG_DIRS: "/kafka/logs1"
      KAFKA_LOG_RETENTION_MINUTES: 60
      KAFKA_LOG_RETENTION_BYTES: 1024000
    volumes:
      - ./kafka/data:/kafka
  kafka2:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: kafka2
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_BROKER_ID: 2
      KAFKA_MESSAGE_MAX_BYTES: 512
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_CREATE_TOPICS: "rplace:1:3:compact"
      KAFKA_LOG_DIRS: "/kafka/logs2"
      KAFKA_LOG_RETENTION_MINUTES: 60
      KAFKA_LOG_RETENTION_BYTES: 1024000
    volumes:
      - ./kafka/data:/kafka
  kafka3:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: kafka3
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_BROKER_ID: 3
      KAFKA_MESSAGE_MAX_BYTES: 512
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_CREATE_TOPICS: "rplace:1:3:compact"
      KAFKA_LOG_DIRS: "/kafka/logs3"
      KAFKA_LOG_RETENTION_MINUTES: 60
      KAFKA_LOG_RETENTION_BYTES: 1024000
    volumes:
      - ./kafka/data:/kafka
